= Go Bytify

A dead simple library for writing various types to byte buffers.

Bytify is intended for those who pursue senseless, borderline silly
micro-optimizations. If that's not you, consider using the standard library's
`strconv.Append*()` functions instead.

Bytify also has no dependencies on any outside or standard library packages, so
you can soak up that minimized assembly while you revel in the nanoseconds that
you're saving.

== Usage

.Install
[source,sh-session]
----
$ go get github.com/vulpine-io/lib-go-bytify
----

.Example Usage
[source,go]
----
package main

import (
  "fmt"
  "github.com/foxcapades/go-bytify/v0/bytify"
)

func main() {
  value := uint64(123_456_789_123)
  buf := make([]byte, bytify.Uint64StringSize(value))
  bytify.Uint64ToBytes(value, buf)

  fmt.Println(string(buf)) // 123456789123
}
----

== Benchmarks

Benchmark output is stored in `docs/benchmarks`. each file was generated by the
benchmark script `\{version}/tools/bench/main.go`.

The cycles/iterations used is 100 cycles of 10,000,000 iterations each (meaning
1 billion calls to each of the `bytify` and `strconv` functions).

To summarize the results, the bytify functions under test performed ~50.2625ns
faster than the only comparable standard library function `strconv.AppendUint`.

== Change Log

`v0.1.0`::
Added the following feature complete methods with full test coverage:
+
.Serialization Methods
[cols="1m,2m",options="header"]
|===
| Type | Functions
| uint8 | Uint8ToBytes(uint8, []byte) +
Uint8ToBuf(uint8, io.Writer)
| uint16 | Uint16ToBytes(uint16, []byte) +
Uint16ToBuf(uint16, io.Writer)
| uint32 | Uint32ToBytes(uint32, []byte) +
Uint32ToBuf(uint32, io.Writer)
| uint64 | Uint64ToBytes(uint64, []byte) +
Uint64ToBuf(uint64, io.Writer)
|===
+
.Sizing Methods
[cols="1m,2m",options="header"]
|===
| Type   | Functions
| uint8  | Uint8StringSize(uint8)
| uint16 | Uint16StringSize(uint16)
| uint32 | Uint32StringSize(uint32)
| uint64 | Uint64StringSize(uint64)
|===
+
There will be no breaking changes to these functions before `v1.0.0` is released.

